server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true

spring:
  application:
    name: note

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jmx:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_note?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  config:
    type: signed
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 400000
      circuitBreaker:
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 20000000
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        readTimeout: 300000
